[package]
name = "canyon-sys"
version = "0.1.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/Canyon-ml/canyon-sys"
description = "A sys crate for the Canyon ML Project"
readme = "README.md"

[build-dependencies]
bindgen = "0.66.1"
